"""remove parent

Revision ID: d0b4b6820b62
Revises: 65d696075364
Create Date: 2024-05-06 15:07:11.313765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0b4b6820b62'
down_revision: Union[str, None] = '65d696075364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'parent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('parent', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
